### ISSUE TITLE
Speed Up Unit Tests

### ISSUE THREAD

**Issue by aenglander** [iovation/launchkey-python#21]
The tests are now taking over 10 seconds to run. They used to take 4 seconds. Not a huge priority but this could get out of hand quickly.

**Comment by bgroveben** [comment]
I may be able to help with your [testing timing troubles using stestr.](https://github.com/mtreinish/stestr)  
Go ahead, say it 5 times fast, it’s fun.  
Anyhow, after I installed the all of the required packages for **launchkey-python** locally, I ran your testing suite on my machine.  
Check out the results:

```
======
Totals
======
Ran: 511 tests in 4.6313 sec.
 - Passed: 511
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 0
Sum of execute time for each test: 28.1104 sec.

==============
Worker Balance
==============
 - Worker 0 (64 tests) => 0:00:04.618411
 - Worker 1 (64 tests) => 0:00:04.621486
 - Worker 2 (64 tests) => 0:00:02.672087
 - Worker 3 (64 tests) => 0:00:02.759103
 - Worker 4 (64 tests) => 0:00:03.865298
 - Worker 5 (64 tests) => 0:00:03.222005
 - Worker 6 (64 tests) => 0:00:04.599389
 - Worker 7 (63 tests) => 0:00:01.884142
```

[Here is a link](https://github.com/bgroveben/launchkey-python) to my repo fork that _**doesn’t**_ exclude the test runner files from version control (my fork, my rules, evil laugh, etc).  

I made the `stestr_terminal_output.txt` file myself for a quick results summary, but the `.stestr` directory in the root directory will have lots of log files and results-type stuff that software architects and engineers know more about than I do. The runner can be tweaked in the `.stestr.conf` file. [Docs are here](https://stestr.readthedocs.io/en/latest/index.html) if you want them. The project looks promising, however there are 15 issues in their stats; not as many as my last ex, but enough to be concerned. I read that it was implemented on [OpenStack](https://wiki.openstack.org/wiki/Testr), but I'm not going to send you down any more rabbit-holes that you can find on your own.

`stestr` looks promising, but I think I can do better.  

[I found a blog post](http://jhshi.me/2016/10/04/python-testing-using-pytest-tox-travis-ci-and-coverall/index.html) about an engineer who implemented a testing-CI-reporting pipeline using Pytest, TravisCI and tox, along with with Coverage and Coveralls. Fortunately, all of that stuff can play nice with your `unittest` unit tests (sorry, redundancy in testing  and writing is a waste of time, I know). Hopefully some of this will actually be useful to you, and if so please let me know what you think. In the meantime, I'll see what else I can learn that might help out.

**Comment by bgroveben** [comment]
@aenglander I tried some other test runners and got typical runtimes for:

```$ python3 -m unittest``` 
```
>>>
 ...............  Ran 511 tests in 10.917s  
```  
  
```$ python3 -m pytest```
```
>>> 
tests/test_base_client.py .........                                      [  1%]
tests/test_base_transport.py ...                                         [  2%]
tests/test_directory_client.py ......................................... [ 10%]
.....................................                                    [ 17%]
tests/test_factories.py ...........                                      [ 19%]
tests/test_jose_auth_transport.py ...................................... [ 27%]
................................................................         [ 39%]
tests/test_organization_client.py ...................................... [ 47%]
................................................................         [ 59%]
tests/test_requests_http_transport.py ............                       [ 62%]
tests/test_service_client.py ........................................... [ 70%]
......................................................................   [ 84%]
tests/test_service_security_policy.py ...............                    [ 87%]
tests/test_utils.py .................................................... [ 97%]
......                                                                   [ 98%]
tests/test_validation.py ........                                        [100%]

========================= 511 passed in 12.50 seconds ==========================
```  


```$ stestr run```  
```
>>> .....
======
Totals
======
Ran: 511 tests in 3.7929 sec.
 - Passed: 511
 - Skipped: 0
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 0
Sum of execute time for each test: 25.1350 sec.

==============
Worker Balance
==============
 - Worker 0 (58 tests) => 0:00:03.503387
 - Worker 1 (63 tests) => 0:00:02.625201
 - Worker 2 (64 tests) => 0:00:03.014298
 - Worker 3 (65 tests) => 0:00:03.278643
 - Worker 4 (65 tests) => 0:00:03.114926
 - Worker 5 (65 tests) => 0:00:03.156894
 - Worker 6 (66 tests) => 0:00:03.312146
 - Worker 7 (65 tests) => 0:00:03.274205
```

Each test runner's times are fairly consistent, with pytest being the slowest, unittest a bit faster, and stestr much faster.

**Comment by aenglander** [comment]
The actual problem here is that is may be tests and it may be code. We need to actually identify the issue. None of the code changes should have made the tests take 6x the original time to run.
